spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: vajith
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

